[tox]
envlist = py35, py36, py37, py38, py39, py310, py311, py312, py313, py314

[testenv]
commands =
    pycodestyle flittpayments
    python -m unittest discover -s tests -p "*_tests.py" -t .
deps =
    pycodestyle<2.6; python_version < "3.6"
    pycodestyle>=2.6; python_version >= "3.6"
    httpx2>=2.0.0,<3.0.0; python_version >= "3.10"
skip_missing_interpreters =
    true
