from typing import Any, TypeVar

from flittpayments._types import RequestData
from flittpayments.resources import Resource

_ResultT = TypeVar('_ResultT')


class Checkout(Resource[_ResultT]):
    def url(self, data: RequestData) -> _ResultT: ...
    def token(self, data: RequestData) -> _ResultT: ...
    def verification(self, data: RequestData) -> _ResultT: ...
    def subscription(self, data: RequestData) -> _ResultT: ...
    def subscription_stop(self, order_id: Any) -> _ResultT: ...
    def open_banking(self, data: RequestData) -> _ResultT: ...
    def installments(self, data: RequestData) -> _ResultT: ...
