from typing import TypeVar

from flittpayments._types import RequestData
from flittpayments.resources import Resource

_ResultT = TypeVar('_ResultT')


class Order(Resource[_ResultT]):
    def settlement(self, data: RequestData) -> _ResultT: ...
    def capture(self, data: RequestData) -> _ResultT: ...
    def capture_full(self, data: RequestData) -> _ResultT: ...
    def reverse(self, data: RequestData) -> _ResultT: ...
    def reverse_full(self, data: RequestData) -> _ResultT: ...
    def status(self, data: RequestData) -> _ResultT: ...
    def fiscal_data(self, data: RequestData) -> _ResultT: ...
