from typing import TypeVar

from flittpayments._types import RequestData
from flittpayments.resources import Resource

_ResultT = TypeVar('_ResultT')


class Pcidss(Resource[_ResultT]):
    def step_one(self, data: RequestData) -> _ResultT: ...
    def step_two(self, data: RequestData) -> _ResultT: ...


class Payment(Resource[_ResultT]):
    def p2pcredit(self, data: RequestData) -> _ResultT: ...
    def ibancredit(self, data: RequestData) -> _ResultT: ...
    def reports(self, data: RequestData) -> _ResultT: ...
    def recurring(self, data: RequestData) -> _ResultT: ...
